
--------------------------------------------  
  Common console commands:
		cd - change directory
  mkdir - make directory
 	ls - view the files/folders in directory
--------------------------------------------  

BEGIN WORKFLOW

--------------------------------------------  
Clone the Repo to local machine:

     $ git clone <remote-repo-url>
--------------------------------------------  
 
There will be two branchs (master, dev) Make sure the local branchs is up-to-date:
 $ git pull origin master
 $ git pull origin dev

Create new branch:
 $ git banch branch_name
 
Move to branch:
 $ git checkout branch_name
 
Navigate file structure as needed:
 $ ls 
 $ cd folder_name
 
Add the files to the branch:
 $ git add .
 
Verify file: 
 $ git status
 
Commit the files:
 $ git commit -m "comment"
 
Add branch and files to the Remote Repo:
 $ git push -u origin branch_name
 
Go to the github website to manage pull request and merge. 
 
Switch back to local master so you can delete the local branch:
 $ git checkout master
 
Delete local branch: 
 $ git branch -d branch_name
 OR 
 $ git branch -D branch_name
 
 If you don't want to go to the website, you can merge your branch 
 to the master locally and push the new master to the remote repo:
 
Switch back to master branch:
 $ git checkout master
 
Merge the branch with the local master:
 $ git merge branch_name -m "comment"
 
Push the local master to the remote master:
 $ git push origin main
 
Delete local branch: 
 $ git branch -d branch_name
 OR 
 $ git branch -D branch_name
